[package]
name = "pvm-rs"
version = "0.1.0"
edition = "2021"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5"
rich-phantoms = { git = "https://github.com/djmcgill/rich_phantoms" }